Select states from git repo
Also comply with shellcheck

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,6 +1,9 @@
 #!/bin/bash
+# shellcheck disable=2035
 # Forked from https://github.com/mdaffin/salt-arch
 set -Eeuo pipefail
+
+# shellcheck disable=2154
 trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
 fail() { echo >&2 "$@"; exit 1; }
 
@@ -28,6 +31,64 @@ if ! gpg --check-sigs $publicKeyFingerprint; then
 fi
 
 #####################################################################
+## Select disk
+#####################################################################
+
+devicelist="$(lsblk -dplnx size -o name,size | grep -Ev "boot|rpmb|loop" | tac)"
+# shellcheck disable=2086
+device="$(dialog --stdout --menu "Select disk to format" 0 0 0 $devicelist)"
+clear
+
+if [ -z "$device" ]; then
+    fail "No disk selected. Aborting."
+fi
+
+#####################################################################
+## Save stdout and stderr to file
+#####################################################################
+
+exec 1> >(tee -ia bootstrap.stdout.log)
+exec 2> >(tee -ia bootstrap.stderr.log >&2)
+
+#####################################################################
+## Setup the disk and partitions
+#####################################################################
+
+parted --script "$device" -- mktable gpt \
+    mkpart primary ext2 1Mib 2MiB \
+    set 1 bios_grub on \
+    mkpart primary ext4 2MiB 100%
+
+partition="${device}2"
+mkfs.ext4 "$partition"
+mount "$partition" /mnt
+
+#####################################################################
+## Install Arch Linux
+#####################################################################
+
+pacstrap /mnt base grub git gnupg python2-gnupg salt
+genfstab -U /mnt >> /mnt/etc/fstab
+
+arch-chroot /mnt sh -c "grub-install --target=i386-pc $device \
+    && grub-mkconfig -o /boot/grub/grub.cfg"
+
+#####################################################################
+## Download and verify salt states
+#####################################################################
+
+gpg --export -a $publicKeyFingerprint | arch-chroot /mnt sh -c "gpg --import"
+
+arch-chroot /mnt sh -c "mkdir -p /srv/{salt,formulas,pillar}"
+arch-chroot /mnt sh -c "git clone $formulaGitRemote $formulaGitDir"
+arch-chroot /mnt sh -c "cp $formulaGitDir/pre-commit $formulaGitDir/.git/hooks"
+
+if ! arch-chroot /mnt sh -c "cd $formulaGitDir && git verify-commit HEAD"; then
+    fail "GPG signature check failed!"
+fi
+
+
+#####################################################################
 ## Select username
 #####################################################################
 
@@ -53,16 +114,26 @@ fi
 ## Select states
 #####################################################################
 
+pushd /mnt/$formulaGitDir/$formulaId
+shopt -s nullglob
+
+slsItems=""
+for state in */init.sls; do
+    slsItems="$slsItems $(dirname "$state") off"
+done
+for state in *.sls; do
+    if [ "$state" != "core.sls" ]; then
+        slsItems="$slsItems ${state//.sls/} off" # $(echo "$state" | sed 's/\(.*\).sls$/\1/') off"
+    fi
+done
+
+popd
+shopt -u nullglob
+
+# shellcheck disable=2086
 states="$(dialog --stdout --no-items \
-    --checklist "Select states" \
-    0 0 0 \
-    system  on  \
-    wm      on  \
-    dev     on  \
-    browser on  \
-    backup  off \
-    laptop  off \
-)"
+    --checklist "Select states (core included by default)" \
+    0 0 0 $slsItems )"
 clear
 
 if [ -z "$states" ]; then
@@ -70,62 +141,10 @@ if [ -z "$states" ]; then
 fi
 
 #####################################################################
-## Select disk
+## Setup new Salt configuration
 #####################################################################
 
-devicelist="$(lsblk -dplnx size -o name,size | grep -Ev "boot|rpmb|loop" | tac)"
-device="$(dialog --stdout --menu "Select disk to format" 0 0 0 $devicelist)"
-clear
-
-if [ -z "$device" ]; then
-    fail "No disk selected. Aborting."
-fi
-
-#####################################################################
-## Save stdout and stderr to file
-#####################################################################
-
-exec 1> >(tee -ia bootstrap.stdout.log)
-exec 2> >(tee -ia bootstrap.stderr.log >&2)
-
-#####################################################################
-## Setup the disk and partitions
-#####################################################################
-
-parted --script $device -- mktable gpt \
-    mkpart primary ext2 1Mib 2MiB \
-    set 1 bios_grub on \
-    mkpart primary ext4 2MiB 100%
-
-partition="${device}2"
-mkfs.ext4 $partition
-mount $partition /mnt
-
-#####################################################################
-## Install Arch Linux
-#####################################################################
-
-pacstrap /mnt base grub git gnupg python2-gnupg salt
-genfstab -U /mnt >> /mnt/etc/fstab
-
-arch-chroot /mnt sh -c "grub-install --target=i386-pc $device \
-    && grub-mkconfig -o /boot/grub/grub.cfg"
-
-#####################################################################
-## Prepare and verify salt states and configuration
-#####################################################################
-
-gpg --export -a $publicKeyFingerprint | arch-chroot /mnt sh -c "gpg --import"
-
-arch-chroot /mnt sh -c "mkdir -p /srv/{salt,formulas,pillar}"
-arch-chroot /mnt sh -c "git clone $formulaGitRemote $formulaGitDir"
-arch-chroot /mnt sh -c "cp $formulaGitDir/pre-commit $formulaGitDir/.git/hooks"
-
-if ! arch-chroot /mnt sh -c "cd $formulaGitDir && git verify-commit HEAD"; then
-    fail "GPG signature check failed!"
-fi
-
-echo $hostname > /mnt/etc/salt/minion_id
+echo "$hostname" > /mnt/etc/salt/minion_id
 
 cat >/mnt/etc/salt/minion <<EOF
 state_verbose: False
@@ -171,7 +190,7 @@ rm /usr/bin/pinentry # Default symlink to pinentry-gtk-2
 ln -s /usr/bin/pinentry-tty /usr/bin/pinentry
 
 while ! gpg --card-status; do
-    read -p "Insert yubikey and hit ENTER to continue ..."
+    read -rp "Insert yubikey and hit ENTER to continue ..."
 done
 
 ( umask 077 && gpg -d $pillarGpg > /mnt$pillar )
@@ -200,5 +219,5 @@ EOF
 umount -R /mnt
 clear
 
-echo -e "\nBootstrap complete! \n\nReboot when ready to continue installation.\n"
+echo -e '\nBootstrap complete! \n\nReboot when ready to continue installation.\n'
 
