Manage secrets in bootstrap

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -3,25 +3,32 @@
 set -uo pipefail
 trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
 
+fail() {
+  echo >&2 "$@"
+  exit 1
+}
+
 if grep -qs /mnt /proc/mounts; then
-    echo "/mnt is already mounted. Unmount it first, or edit this script." >&2
-    exit 1
+    fail "/mnt is already mounted. Unmount it first, or edit this script."
 fi
+
+if [ ! -f laptop-pillar-secrets.gpg ]; then
+    fail "Missing laptop-pillar-secrets.gpg. Copy into current dir and try again"
+fi
+
+gpgKeyUrl=https://keybase.io/atmoz/pgp_keys.asc
+saltStateRepo=https://github.com/atmoz/salt-laptop.git
 
 devicelist=$(lsblk -dplnx size -o name,size | grep -Ev "boot|rpmb|loop" | tac)
 device=$(dialog --stdout --menu "Select installtion disk" 0 0 0 ${devicelist}) || exit 1
 clear
 
-### Set up logging ###
-exec 1> >(tee "stdout.log")
-exec 2> >(tee "stderr.log")
-
 ### Setup the disk and partitions ###
 parted --script "${device}" -- mklabel gpt \
-mkpart primary fat32 1Mib 2MiB \
-set 1 boot on \
-mkpart primary ext4 2MiB 10GiB \
-mkpart primary ext4 10GiB 100%
+    mkpart primary fat32 1Mib 2MiB \
+    set 1 boot on \
+    mkpart primary ext4 2MiB 10GiB \
+    mkpart primary ext4 10GiB 100%
 
 # Simple globbing was not enough as on one device I needed to match /dev/mmcblk0p1
 # but not /dev/mmcblk0boot1 while being able to match /dev/sda1 on other devices.
@@ -33,16 +40,32 @@ mkfs.ext4 "${part_root}"
 mkfs.ext4 "${part_home}"
 
 mount "${part_root}" /mnt
-pacstrap /mnt base salt python2-pygit2 git gpg wireless_tools
+pacstrap /mnt base salt git gnupg wireless_tools
 
 echo "atmoz-laptop" > /mnt/etc/hostname
 genfstab -t PARTUUID /mnt >> /mnt/etc/fstab
 
-arch-chroot /mnt sh -c "curl https://keybase.io/atmoz/pgp_keys.asc | gpg --import"
-arch-chroot /mnt sh -c "git clone https://github.com/atmoz/salt-laptop.git /srv/salt"
+arch-chroot /mnt sh -c "curl $gpgKeyUrl | gpg --import"
+arch-chroot /mnt sh -c "git clone $saltStateRepo /srv/salt"
 if ! arch-chroot /mnt sh -c "cd /srv/salt && git verify-commit HEAD"; then
-    echo "GPG signature check failed!" >&2
-    exit 1
+    fail "GPG signature check failed!"
 fi
 
-arch-chroot /mnt sh -c "cd /srv/salt && ./salt-call state.apply pillar='{"bootstrap": True}'"
+cat >/mnt/etc/salt/minion <<EOF
+file_client: local
+file_roots:
+  base:
+    - /srv/salt/states
+pillar_roots:
+  base:
+    - /srv/salt/pillar
+EOF
+
+# Use pinentry-curses to unlock yubikey
+rm /usr/bin/pinentry
+ln -s /usr/bin/pinentry-curses /usr/bin/pinentry
+
+curl $gpgKeyUrl | gpg --import
+gpg -d /tmp/laptop-pillar-secrets.gpg > /srv/salt/pillar/secrets.sls
+
+arch-chroot /mnt sh -c "salt-call state.apply pillar='{\"bootstrap\": True}'"
