Only check encrypted file if it's not decrypted

diff --git a/salt-call b/salt-call
--- a/salt-call
+++ b/salt-call
@@ -5,12 +5,12 @@ repo="$(dirname "$(readlink -f "$0")")"
 encrypted=/home/atmoz/.password-store/private/laptop-pillar-secrets.gpg
 tempSecrets=$repo/pillar/secrets.sls
 
-if [ ! -f "$encrypted" ]; then
-    echo "Missing $encrypted" >&2
-    exit 1
-fi
-
 if [ ! -f "$tempSecret" ]; then
+    if [ ! -f "$encrypted" ]; then
+        echo "Missing $encrypted" >&2
+        exit 1
+    fi
+
     # decrypt pillar data with normal user, save to file as root
     ( umask 077 && gpg -qd $encrypted | sudo tee $tempSecrets > /dev/null )
 fi
